### PR TITLE
Sample at every tick

### PR DESCRIPTION
**Pull request by leiradel**
The beeper misses some input values because the input state is only ever used when needed to produce an output sample. Sound quality suffers, I noticed it when comparing the Nonamed intro music with Fuse.

This PR takes every beeper tick into account, using the average when an output sample is required. Nonamed now sounds extremely similar to Fuse when configured to not use audio filters.

I've decreased the buffer because 512 made it sound a bit muffled. Both the sampling scheme and the buffer size were suggested by MartianGirl, who has all the merit.

I'm not sure if the change applies to systems other than the ZX Spectrum, I'm not familiar with them.

I'm also not sure if the comment below applies anymore, so I left it in the source code:

```c
/* DC adjustment filter from StSound, this moves an "offcenter"
   signal back to the zero-line (e.g. the volume-level output
   from the chip simulation which is >0.0 gets converted to
   a +/- sample value)
*/
```

[comparison.zip](https://github.com/user-attachments/files/16099841/comparison.zip)

### CODE REVIEW

**Comment by floooh** [comment]
Hmm interesting, I need to try this fix in the other systems.

I know that the chips audio emulators generally suffer from frequency aliasing (except maybe the SID emulator), so I'll generally need to do more research into that area (also how other emulators solve those problems).

Do you why Github thinks that your change has a merge collision? The beeper.h file in the chips repository had its last change 2 years ago 🤔

**Comment by leiradel** [comment]
How odd, I can do another PR if you prefer.

**Comment by leiradel** [comment]
I think I solved the "conflict".

**Comment by floooh** [comment]
You're right, it *does* sound better. Mainly regular "beeps" like the error beep on the KC85, or the Popcorn bootup sound on the LC-80...

I'll merge and then also update the emulators webpage. Many thanks!

As I said, I'll also look into the aliasing problem (which at least the AY emulation still suffers from ... maybe it's actually a similar problem...).

**Comment by floooh** [comment]
...and merged :)

**Comment by floooh** [comment]
Ok, the webpage at https://floooh.github.io/tiny8bit/ will be updated when this CI pipeline finishes: https://github.com/floooh/chips-test/actions/runs/9796642006

**Comment by leiradel** [comment]
> You're right, it _does_ sound better

Awesome! Again, credits go to MartianGirl, author of [SpecIde](https://github.com/MartianGirl/SpecIde).

**Comment by leiradel** [comment]
Just to make it clear, I didn't look into her source code, which is GPL (though maybe it would be considered fair?), but she explained it to me and I changed `beeper.h` based on the explanation.

**Comment by floooh** [comment]
Good point, but IMHO that should be totally fine.

**Pull request merged**
